import AppKit

/// A faithful copy of a pasteboard's contents: every item, every type, as
/// raw data - so a copied image, file or rich text survives our brief
/// borrowing of the clipboard, not just plain strings.
///
/// Lives in memory only, for the second or so a correction takes.
public struct PasteboardSnapshot: Sendable {

    /// One pasteboard item: its types in order, with each type's data.
    public struct Item: Sendable {
        public var representations: [(type: String, data: Data)]

        public init(representations: [(type: String, data: Data)]) {
            self.representations = representations
        }
    }

    public private(set) var items: [Item]

    public static let empty = PasteboardSnapshot(items: [])

    init(items: [Item]) {
        self.items = items
    }

    /// Snapshots larger than this are not captured type by type; see `capture`.
    static let maximumBytes = 64 * 1024 * 1024

    @MainActor
    public static func capture(from pasteboard: NSPasteboard) -> PasteboardSnapshot {
        var items: [Item] = []
        var total = 0
        for item in pasteboard.pasteboardItems ?? [] {
            var representations: [(type: String, data: Data)] = []
            for type in item.types {
                // Reading the data also resolves lazily promised content.
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                // A gigantic clipboard (a copied video) is not worth holding
                // twice in memory; keep what fits and stop.
                guard total <= maximumBytes else { break }
                representations.append((type.rawValue, data))
            }
            if !representations.isEmpty {
                items.append(Item(representations: representations))
            }
        }
        return PasteboardSnapshot(items: items)
    }

    /// Puts the snapshot back. Pasteboard items cannot be re-added once they
    /// belonged to a pasteboard, so fresh items are built from the data.
    @MainActor
    public func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored: [NSPasteboardItem] = items.map { item in
            let pasteboardItem = NSPasteboardItem()
            for representation in item.representations {
                pasteboardItem.setData(representation.data, forType: NSPasteboard.PasteboardType(representation.type))
            }
            return pasteboardItem
        }
        pasteboard.writeObjects(restored)
    }
}

/// Marker types from nspasteboard.org. Clipboard managers (Maccy, Paste,
/// Raycast, Alfred...) skip content carrying them, so the text we place on
/// the clipboard for a moment never lands in the user's clipboard history.
public enum TransientPasteboard {

    static let markerTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.ConcealedType"
    ]

    /// Replaces the pasteboard contents with `text`, tagged as transient.
    /// Returns the change count after the write, so the caller can later tell
    /// whether someone else has written to the pasteboard since.
    @MainActor
    @discardableResult
    public static func write(_ text: String, to pasteboard: NSPasteboard) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for marker in markerTypes {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(marker))
        }
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }
}
