import AppKit
import Carbon.HIToolbox
import GrammarAICore
import Testing
@testable import GrammarAISystem

/// Every test here uses a uniquely named private pasteboard - never the
/// user's real clipboard.
@Suite("Pasteboard snapshot")
@MainActor
struct PasteboardSnapshotTests {

    private func scratch() -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("grammarai-tests-\(UUID().uuidString)"))
    }

    @Test func roundTripsEveryTypeOfEveryItem() {
        let pasteboard = scratch()
        defer { pasteboard.releaseGlobally() }
        let first = NSPasteboardItem()
        first.setString("héllo 👋 שלום", forType: .string)
        first.setData(Data("{\\rtf1 hello}".utf8), forType: .rtf)
        first.setData(Data([0x89, 0x50, 0x4E, 0x47, 0x00, 0xFF]), forType: .png)
        let second = NSPasteboardItem()
        second.setString("file:///tmp/example.txt", forType: .fileURL)
        pasteboard.clearContents()
        pasteboard.writeObjects([first, second])

        let snapshot = PasteboardSnapshot.capture(from: pasteboard)
        TransientPasteboard.write("temporary correction", to: pasteboard)
        #expect(pasteboard.string(forType: .string) == "temporary correction")

        snapshot.restore(to: pasteboard)
        let items = pasteboard.pasteboardItems ?? []
        #expect(items.count == 2)
        #expect(items.first?.string(forType: .string) == "héllo 👋 שלום")
        #expect(items.first?.data(forType: .rtf) == Data("{\\rtf1 hello}".utf8))
        #expect(items.first?.data(forType: .png) == Data([0x89, 0x50, 0x4E, 0x47, 0x00, 0xFF]))
        #expect(items.last?.string(forType: .fileURL) == "file:///tmp/example.txt")
    }

    @Test func anEmptyClipboardIsRestoredAsEmpty() {
        let pasteboard = scratch()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        let snapshot = PasteboardSnapshot.capture(from: pasteboard)
        TransientPasteboard.write("temporary", to: pasteboard)
        snapshot.restore(to: pasteboard)
        #expect(pasteboard.string(forType: .string) == nil)
        #expect((pasteboard.pasteboardItems ?? []).isEmpty)
    }

    @Test func temporaryTextIsMarkedForClipboardManagersToIgnore() {
        let pasteboard = scratch()
        defer { pasteboard.releaseGlobally() }
        let before = pasteboard.changeCount
        let after = TransientPasteboard.write("temporary", to: pasteboard)
        #expect(after > before)
        let types = (pasteboard.types ?? []).map(\.rawValue)
        #expect(types.contains("org.nspasteboard.TransientType"))
        #expect(types.contains("org.nspasteboard.ConcealedType"))
        #expect(types.contains("org.nspasteboard.AutoGeneratedType"))
    }

    @Test func systemClipboardDetectsAnEditorsEmptySelectionCopy() async {
        let name = NSPasteboard.Name("grammarai-tests-\(UUID().uuidString)")
        let pasteboard = NSPasteboard(name: name)
        defer { pasteboard.releaseGlobally() }
        let clipboard = SystemClipboard(name: name)

        pasteboard.clearContents()
        pasteboard.setString("whole line\n", forType: .string)
        pasteboard.setData(Data(#"{"isFromEmptySelection":true}"#.utf8), forType: NSPasteboard.PasteboardType("vscode-editor-data"))
        #expect(await clipboard.isEmptySelectionCopy())

        pasteboard.clearContents()
        pasteboard.setString("a real selection", forType: .string)
        #expect(await !clipboard.isEmptySelectionCopy())
        #expect(await clipboard.plainText() == "a real selection")
    }
}

@Suite("Hotkeys")
@MainActor
struct HotkeyTests {

    @Test func modifiersConvertToCarbonAndBack() {
        let all: KeyCombo.Modifiers = [.command, .shift, .option, .control]
        #expect(all.carbonFlags == UInt32(cmdKey | shiftKey | optionKey | controlKey))
        #expect(KeyCombo.Modifiers(carbonFlags: all.carbonFlags) == all)
        #expect(KeyCombo.Modifiers(carbonFlags: UInt32(cmdKey | shiftKey)) == [.command, .shift])
    }

    @Test func aShortcutWithoutARealModifierIsRefused() {
        let manager = HotkeyManager()
        #expect(throws: HotkeyError.invalidCombination) {
            try manager.register(KeyCombo(keyCode: 5, modifiers: [.shift]))
        }
        #expect(manager.registeredCombo == nil)
    }

    @Test func registersAndUnregistersWithoutAnyPermission() throws {
        // An obscure combination nobody uses, released right away.
        let combo = KeyCombo(keyCode: UInt32(kVK_F19), modifiers: [.command, .shift, .option, .control])
        let manager = HotkeyManager()
        try manager.register(combo)
        #expect(manager.registeredCombo == combo)
        try manager.register(combo) // re-registering replaces, never conflicts with itself
        manager.unregister()
        #expect(manager.registeredCombo == nil)
    }

    @Test func warnsAboutShortcutsEveryAppUses() {
        let copy = HotkeyConflicts.conflict(for: KeyCombo(keyCode: 8, modifiers: [.command]))
        #expect(copy != nil)
        let findPrevious = HotkeyConflicts.conflict(for: .defaultCorrection)
        #expect(findPrevious?.severity == .common)
        #expect(findPrevious?.message.contains("Find Previous") == true)
        #expect(HotkeyConflicts.conflict(for: KeyCombo(keyCode: UInt32(kVK_F19), modifiers: [.control, .option])) == nil)
    }

    @Test func readsTheSystemShortcutTable() {
        #expect(!HotkeyConflicts.systemShortcuts().isEmpty)
    }

    @Test func resolvesCopyAndPasteKeysForTheCurrentLayout() {
        let c = KeyboardLayout.keyCode(forCommandCharacter: "c", fallback: KeyboardLayout.ansiC)
        let v = KeyboardLayout.keyCode(forCommandCharacter: "v", fallback: KeyboardLayout.ansiV)
        #expect(c < 128)
        #expect(v < 128)
        #expect(c != v)
    }

    @Test func labelsShortcutKeys() {
        #expect(!KeyCombo.defaultCorrection.localizedDisplayString.isEmpty)
        #expect(KeyCombo(keyCode: 49, modifiers: [.control]).localizedDisplayString == "\u{2303}Space")
    }

    @Test func terminalsAreRecognised() {
        #expect(FrontmostApp(processID: 1, bundleID: "com.apple.Terminal", name: nil).isTerminal)
        #expect(!FrontmostApp(processID: 1, bundleID: "com.apple.Safari", name: nil).isTerminal)
        #expect(!FrontmostApp(processID: 1, bundleID: nil, name: nil).isTerminal)
    }
}
